<a href="https://colab.research.google.com/github/basaanithanaveenkumar/KNN-Based-Recommendation-system/blob/master/Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import** all the dependencis requires for the given notebook

In [7]:
import pandas as pd

In [8]:
rest=pd.read_csv("res.csv")

#data frame from json file

In [9]:
rest.head(5)

   Unnamed: 0  ...               8
0           0  ...  (604) 559-8999
1           1  ...  (604) 568-1344
2           2  ...         Unknown
3           3  ...         Unknown
4           4  ...  (604) 559-7968

[5 rows x 10 columns]

In [6]:
rest_rev=pd.read_csv("res_rev.csv")

FileNotFoundError: ignored

# Data cleaning

In [10]:
rest.head(5)

   Unnamed: 0  ...               8
0           0  ...  (604) 559-8999
1           1  ...  (604) 568-1344
2           2  ...         Unknown
3           3  ...         Unknown
4           4  ...  (604) 559-7968

[5 rows x 10 columns]

In [11]:
rest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  266 non-null    int64
 1   0           266 non-null    object
 2   1           266 non-null    object
 3   2           266 non-null    object
 4   3           266 non-null    object
 5   4           266 non-null    object
 6   5           266 non-null    object
 7   6           266 non-null    object
 8   7           266 non-null    object
 9   8           261 non-null    object
dtypes: int64(1), object(9)
memory usage: 20.9+ KB

# rename the columns with proper tags

In [12]:
rest=rest.rename(columns={'Unnamed: 0':'index','0':'Name','1':'Price','2':'Type of Cusine','3':'Timing ','4':'Address','5':'coordinates','6':'LandMark','7':'website','8':'Phone'})

In [13]:
rest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           266 non-null    int64
 1   Name            266 non-null    object
 2   Price           266 non-null    object
 3   Type of Cusine  266 non-null    object
 4   Timing          266 non-null    object
 5   Address         266 non-null    object
 6   coordinates     266 non-null    object
 7   LandMark        266 non-null    object
 8   website         266 non-null    object
 9   Phone           261 non-null    object
dtypes: int64(1), object(9)
memory usage: 20.9+ KB

In [14]:
rest[['coordinates']]

                                   coordinates
0    ['49.2827049205371', '-123.106144577322']
1               ['49.2751066', '-123.1220961']
2                ['49.2679331', '-123.149019']
3                 ['49.278431', '-123.098205']
4               ['49.2837849', '-123.1066087']
..                                         ...
261               ['49.252851', '-123.101296']
262             ['49.2642369', '-123.1690986']
263             ['49.2890947', '-123.1326326']
264             ['49.2305821', '-123.0902399']
265               ['49.283194', '-123.104445']

[266 rows x 1 columns]

In [15]:
rest['Price'] = rest['Price'].replace({ '$$$$$ ': 5,'$$$ ': 3, '$$$$ ': 4, '$$ ': 2,'$ ':1})

In [16]:
rest

     index  ...           Phone
0        0  ...  (604) 559-8999
1        1  ...  (604) 568-1344
2        2  ...         Unknown
3        3  ...         Unknown
4        4  ...  (604) 559-7968
..     ...  ...             ...
261    261  ...  (604) 423-4840
262    262  ...         Unknown
263    263  ...         Unknown
264    264  ...         Unknown
265    265  ...         Unknown

[266 rows x 10 columns]

In [17]:
rest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           266 non-null    int64
 1   Name            266 non-null    object
 2   Price           266 non-null    object
 3   Type of Cusine  266 non-null    object
 4   Timing          266 non-null    object
 5   Address         266 non-null    object
 6   coordinates     266 non-null    object
 7   LandMark        266 non-null    object
 8   website         266 non-null    object
 9   Phone           261 non-null    object
dtypes: int64(1), object(9)
memory usage: 20.9+ KB

In [27]:
rest['lati'] = rest['lati'].replace({"'":"","'":""})

In [19]:
rest[['lat','long']] = rest.coordinates.str.split(",",expand=True)

In [20]:
rest[['lat1','lati']] = rest.lat.str.split("[",expand=True)

In [21]:
rest[['longit','longi']] = rest.long.str.split("]",expand=True)

In [22]:
#rest["lati"] = pd.to_numeric(rest["lati"])

ValueError: ignored

In [26]:
rest.drop(columns=['lat1','lat','longi','long'])

     index                       Name  ...                lati                longit
0        0          Tuc Craft Kitchen  ...  '49.2827049205371'   '-123.106144577322'
1        1  The Flying Pig - Yaletown  ...        '49.2751066'        '-123.1220961'
2        2                      Fable  ...        '49.2679331'         '-123.149019'
3        3                 Phnom Penh  ...         '49.278431'         '-123.098205'
4        4   The Flying Pig - Gastown  ...        '49.2837849'        '-123.1066087'
..     ...                        ...  ...                 ...                   ...
261    261                  Published  ...         '49.252851'         '-123.101296'
262    262             Ramen Densetsu  ...        '49.2642369'        '-123.1690986'
263    263           Kosoo Restaurant  ...        '49.2890947'        '-123.1326326'
264    264               Simple Bites  ...        '49.2305821'        '-123.0902399'
265    265               Twisted Fork  ...         '49.283194'         '-123.104445'

[266 rows x 12 columns]

In [28]:
rest.head(6)

   index                       Name  ...                longit longi
0      0          Tuc Craft Kitchen  ...   '-123.106144577322'
1      1  The Flying Pig - Yaletown  ...        '-123.1220961'
2      2                      Fable  ...         '-123.149019'
3      3                 Phnom Penh  ...         '-123.098205'
4      4   The Flying Pig - Gastown  ...        '-123.1066087'
5      5            Guu with Garlic  ...         '-123.133953'

[6 rows x 16 columns]

In [32]:
rest['latitude'] =rest.lati.str.replace("'", '')

In [33]:
rest['longitude'] =rest.longit.str.replace("'", '')

In [36]:
rest.drop(columns=['lat','lat1','lati','long','longit','longi'])

     index                       Name  ...          latitude           longitude
0        0          Tuc Craft Kitchen  ...  49.2827049205371   -123.106144577322
1        1  The Flying Pig - Yaletown  ...        49.2751066        -123.1220961
2        2                      Fable  ...        49.2679331         -123.149019
3        3                 Phnom Penh  ...         49.278431         -123.098205
4        4   The Flying Pig - Gastown  ...        49.2837849        -123.1066087
..     ...                        ...  ...               ...                 ...
261    261                  Published  ...         49.252851         -123.101296
262    262             Ramen Densetsu  ...        49.2642369        -123.1690986
263    263           Kosoo Restaurant  ...        49.2890947        -123.1326326
264    264               Simple Bites  ...        49.2305821        -123.0902399
265    265               Twisted Fork  ...         49.283194         -123.104445

[266 rows x 12 columns]

In [34]:
rest

     index                       Name  ...          latitude           longitude
0        0          Tuc Craft Kitchen  ...  49.2827049205371   -123.106144577322
1        1  The Flying Pig - Yaletown  ...        49.2751066        -123.1220961
2        2                      Fable  ...        49.2679331         -123.149019
3        3                 Phnom Penh  ...         49.278431         -123.098205
4        4   The Flying Pig - Gastown  ...        49.2837849        -123.1066087
..     ...                        ...  ...               ...                 ...
261    261                  Published  ...         49.252851         -123.101296
262    262             Ramen Densetsu  ...        49.2642369        -123.1690986
263    263           Kosoo Restaurant  ...        49.2890947        -123.1326326
264    264               Simple Bites  ...        49.2305821        -123.0902399
265    265               Twisted Fork  ...         49.283194         -123.104445

[266 rows x 18 columns]

In [37]:
rest.to_csv('fin.csv')

In [ ]:
##recommondation system using RBM